# Generated by Django 4.2.3 on 2023-11-13 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0004_alter_realtor_email'),
        ('contacts', '0002_rentcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='realtor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='realtors.realtor'),
            preserve_default=False,
        ),
    ]
