# Generated by Django 4.2.3 on 2023-11-13 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_realtor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='realtor_id',
            new_name='realtor',
        ),
    ]
