# Generated by Django 4.2.3 on 2023-11-13 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0004_alter_realtor_email'),
        ('contacts', '0004_rename_realtor_id_contact_realtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcontact',
            name='realtor',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='realtors.realtor'),
            preserve_default=False,
        ),
    ]
