# Generated by Django 4.2.6 on 2023-11-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_bathrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='has_tv',
            field=models.BooleanField(default=False),
        ),
    ]
