# Generated by Django 4.2.6 on 2023-11-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_hotelroom_has_tv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelroom',
            old_name='is_air_conditioned',
            new_name='has_air_conditioned',
        ),
        migrations.RenameField(
            model_name='hotelroom',
            old_name='is_pet_friendly',
            new_name='has_pet_friendly',
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='has_tv',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
