# Generated by Django 4.2.6 on 2023-11-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_rename_is_air_conditioned_hotelroom_has_air_conditioned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='has_tv',
            field=models.BooleanField(default=False),
        ),
    ]
