# Generated by Django 4.2.6 on 2023-11-06 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0004_alter_realtor_email'),
        ('listings', '0009_remove_listing_lot_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtors.realtor'),
        ),
    ]
