# Generated by Django 4.2.6 on 2023-11-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_alter_listing_address_alter_listing_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='contact_information',
            field=models.PositiveIntegerField(),
        ),
    ]
