# Generated by Django 4.2.6 on 2023-11-07 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0004_alter_realtor_email'),
        ('listings', '0012_alter_hotelroom_contact_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='realtor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='realtors.realtor'),
            preserve_default=False,
        ),
    ]
