# Generated by Django 4.2.6 on 2023-11-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_hotelroom_realtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='no_of_beds',
            field=models.PositiveSmallIntegerField(default=1, null=True),
        ),
    ]
