# Generated by Django 4.2.6 on 2023-11-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_alter_listing_address_alter_listing_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='contact_info',
            field=models.PositiveBigIntegerField(blank=True, default=9026137470),
            preserve_default=False,
        ),
    ]
