# Generated by Django 4.2.6 on 2023-11-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_rentedhotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentedhotel',
            name='amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentedhotel',
            name='days',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
