# Generated by Django 4.2.6 on 2023-11-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_rentedhotel_amount_rentedhotel_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentedhotel',
            old_name='hotel_id',
            new_name='hotel',
        ),
        migrations.RenameField(
            model_name='rentedhotel',
            old_name='user_id',
            new_name='user',
        ),
    ]
