# Generated by Django 4.2.6 on 2023-11-08 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_rename_hotel_id_rentedhotel_hotel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentedhotel',
            name='days',
        ),
        migrations.AddField(
            model_name='rentedhotel',
            name='Check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentedhotel',
            name='check_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
