# Generated by Django 4.2.4 on 2023-11-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_rename_check_out_rentedhotel_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentedhotel',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
