# Generated by Django 4.2.4 on 2023-11-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_rentedhotel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
