# Generated by Django 4.2.4 on 2023-11-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_hotelroom_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentedhotel',
            name='isRated',
            field=models.BooleanField(default=False),
        ),
    ]
