# Generated by Django 4.2.4 on 2023-11-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_rentedhotel_israted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentedhotel',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
