# Generated by Django 4.2.4 on 2023-11-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_alter_rentedhotel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentedhotel',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
