# Generated by Django 4.2.4 on 2023-11-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_rentedhotel_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='rating',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
