# Generated by Django 4.2.3 on 2023-11-11 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_alter_hotelroom_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentedhotel',
            name='reviewDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
